# Generated by Django 2.2.3 on 2019-07-11 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_auto_20190711_2149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='membership',
            new_name='membership_type',
        ),
    ]
