# Generated by Django 2.2.3 on 2019-08-07 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190807_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burst',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
