# Generated by Django 2.2.3 on 2019-08-07 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190807_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='burst',
            name='trackstarz_article',
            field=models.BooleanField(default=False),
        ),
    ]
