# Generated by Django 2.2.3 on 2019-08-08 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_burst_trackstarz_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burst',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='blog.Category'),
        ),
        migrations.AlterField(
            model_name='burst',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
    ]
