# Generated by Django 2.2.3 on 2019-08-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_burst_specialfeature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burst',
            name='overview',
            field=models.TextField(blank=True, default=models.TextField(), null=True),
        ),
    ]
