# Generated by Django 2.2.3 on 2019-08-28 04:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0015_burstlike_commentlike_replylike'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_from_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
