# Generated by Django 2.2.3 on 2019-08-28 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20190828_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burstlike',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='burstlikers', to=settings.AUTH_USER_MODEL),
        ),
    ]
