# Generated by Django 2.2.3 on 2019-09-24 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0022_delete_friendrequest'),
        ('blog', '0021_auto_20190924_0055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='burstlike',
            name='user',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='commentlike',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='user',
        ),
        migrations.RemoveField(
            model_name='replylike',
            name='user',
        ),
        migrations.AddField(
            model_name='burstlike',
            name='author',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='burstlikers', to='userprofile.userprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='userprofile.userprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commentlike',
            name='author',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='commentlikers', to='userprofile.userprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reply',
            name='author',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='userprofile.userprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='replylike',
            name='author',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='replylikers', to='userprofile.userprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reply',
            name='from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_from_user', to='userprofile.userprofile'),
        ),
    ]
