# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateTimeField(auto_created=True)),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=100)),
                ('profilepic', models.ImageField(max_length=200, upload_to=b'')),
                ('coverphoto', models.ImageField(max_length=200, upload_to=b'')),
                ('about', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('youtube', models.URLField()),
                ('twitter', models.URLField()),
                ('instagram', models.URLField()),
                ('snapchat', models.URLField()),
                ('googleplus', models.URLField()),
                ('pinterest', models.URLField()),
                ('website', models.URLField()),
                ('birthdate', models.DateField()),
            ],
        ),
    ]
