# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 22:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_auto_20160508_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profilepic',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
