# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_auto_20160508_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='coverphoto',
            field=models.ImageField(blank=True, upload_to='cover_images'),
        ),
    ]
