# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_auto_20160509_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='coverphoto',
            field=models.ImageField(blank=True, upload_to='cover_images/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, upload_to='profile_images/%Y/%m/%d'),
        ),
    ]
