# Generated by Django 2.2.3 on 2019-07-31 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0011_auto_20190730_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='googleplus',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='snapchat',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pinterest',
            field=models.URLField(blank=True, null=True),
        ),
    ]
