# Generated by Django 2.2.3 on 2019-08-12 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0014_auto_20190812_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='displayname',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
