# Generated by Django 2.2.3 on 2019-08-13 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0016_auto_20190813_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='coverphoto',
            field=models.ImageField(blank=True, default='bw-background_16x9.jpg', upload_to='cover_images/%Y/%m/%d'),
        ),
    ]
