# Generated by Django 2.2.3 on 2019-08-13 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0017_auto_20190813_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='coverphoto',
            field=models.ImageField(blank=True, default='cover_images/2019/08/13/New-Logo-Youtube-2.png', upload_to='cover_images/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, default='profile_images/2019/08/13/New-Trackstarz-App-logo.png', upload_to='profile_images/%Y/%m/%d'),
        ),
    ]
