# Generated by Django 2.2.3 on 2019-08-13 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0018_auto_20190813_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(),
        ),
    ]
