# Generated by Django 2.2.3 on 2019-08-14 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0021_auto_20190813_1822'),
    ]

    operations = [
        migrations.DeleteModel(
            name='friendrequest',
        ),
    ]
